#!/bin/sh


FILENAME=${MYSQL_DATABASE}_$(date +%Y%m%d%H%M)

# generating mysqldump
rm -R /tmp/backup
mkdir /tmp/backup
mysqldump -h $MYSQL_HOST -u $MYSQL_USER -p$MYSQL_PASSWORD $MYSQL_DATABASE | gzip -9 > /tmp/backup/$FILENAME.sql.gz
#cp -R $BACKUP_THIS_FOLDER /tmp/backup/
tar cvf /backups/$FILENAME.tar /tmp/backup/

#copy to remote directory
sshpass -p $SSH_PASS scp -o StrictHostKeyChecking=no /backups/$FILENAME.tar $SSH_USERNAME@$REMOTE_IP:$REMOTE_DIR

# clean up local
find /backups/* -mtime +$DAYS_TO_KEEP -exec rm {} \;

# clean up remote
sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$REMOTE_IP "find $REMOTE_DIR/* -mtime +$DAYS_TO_KEEP -exec rm {} \;"
